<?php
/**
 * Laragon Dashboard - Services API
 * Version: 3.0.0
 * Description: API endpoint for managing services and ports
 */

// Start output buffering to catch any stray output
ob_start();

// Disable error display to prevent JSON corruption
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

// Load configuration
require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../includes/helpers.php';

// Enforce authentication
if (function_exists('check_auth')) {
    check_auth();
}

// Clear any output that may have been generated
ob_clean();

// Set JSON header before any output
header('Content-Type: application/json');

$action = $_GET['action'] ?? 'status';
$serviceName = $_GET['service'] ?? '';

// CSRF check for destructive actions
$destructiveActions = ['start', 'stop', 'restart', 'reload'];
if (in_array($action, $destructiveActions)) {
    $token = $_POST['csrf_token'] ?? ($_GET['csrf_token'] ?? '');
    if (!verifyCSRFToken($token)) {
        ob_clean();
        http_response_code(403);
        echo json_encode(['success' => false, 'error' => 'CSRF token validation failed']);
        ob_end_flush();
        exit;
    }
}

if (!defined('LARAGON_ROOT')) {
    ob_clean();
    http_response_code(500);
    echo json_encode(['success' => false, 'error' => 'Laragon root not defined']);
    ob_end_flush();
    exit;
}

// Service name mapping (systemd service names)
$serviceMap = [
    'Apache' => 'apache2',
    'MySQL' => 'mysql',
    'PostgreSQL' => 'postgresql',
    'Nginx' => 'nginx',
    'Redis' => 'redis-server',
    'Memcached' => 'memcached',
    'MongoDB' => 'mongod',
    'Mailpit' => 'mailpit'
];

// Validate serviceName against whitelist
if (!empty($serviceName) && !isset($serviceMap[$serviceName]) && !in_array($serviceName, $serviceMap)) {
    ob_clean();
    http_response_code(400);
    echo json_encode(['success' => false, 'error' => 'Invalid service name']);
    ob_end_flush();
    exit;
}

// Check systemd service status
function checkServiceStatus($serviceName) {
    $output = @shell_exec('systemctl is-active ' . escapeshellarg($serviceName) . ' 2>&1');
    return trim($output) === 'active' ? 'running' : 'stopped';
}

// Check if a process is running by name
function checkProcessRunning($processName) {
    $output = @shell_exec('ps aux 2>&1');
    return $output && preg_match('/' . preg_quote($processName, '/') . '/', $output);
}

// Get running ports for a service
function getRunningPorts($serviceName, $configPort, $configSSLPort = null) {
    $ports = [];
    if (\LaragonDashboard\Core\Services::isPortInUse($configPort)) {
        $ports[] = $configPort;
    }
    if ($configSSLPort && \LaragonDashboard\Core\Services::isPortInUse($configSSLPort)) {
        $ports[] = $configSSLPort;
    }
    return $ports;
}

// Read laragon.ini
function readLaragonIni() {
    $iniPath = LARAGON_ROOT . '/usr/laragon.ini';
    if (!file_exists($iniPath)) {
        return [];
    }
    
    $oldErrorReporting = error_reporting(0);
    $config = parse_ini_file($iniPath, false, INI_SCANNER_RAW);
    error_reporting($oldErrorReporting);
    
    return $config ?: [];
}

// Write laragon.ini
function writeLaragonIni($config) {
    $iniPath = LARAGON_ROOT . '/usr/laragon.ini';
    
    if (!is_writable($iniPath) && !is_writable(dirname($iniPath))) {
        throw new Exception('Cannot write to laragon.ini file. Check permissions.');
    }
    
    $content = "; Laragon Configuration\n";
    $content .= "; Generated by Laragon Dashboard\n\n";
    
    foreach ($config as $key => $value) {
        // Sanitize key and value to prevent INI injection
        $key = str_replace(["\r", "\n"], "", $key);
        if (is_bool($value)) {
            $value = $value ? '1' : '0';
        } else {
            $value = str_replace(["\r", "\n"], "", $value);
        }
        $content .= $key . ' = ' . $value . "\n";
    }
    
    return file_put_contents($iniPath, $content) !== false;
}

// Start service
function startService($serviceName) {
    global $serviceMap;

    $mappedName = $serviceMap[$serviceName] ?? $serviceName;

    $command = 'sudo systemctl start ' . escapeshellarg($mappedName) . ' 2>&1';
    @exec($command);
    sleep(1); // Wait a bit
    return checkServiceStatus($mappedName) === 'running';
}

// Stop service
function stopService($serviceName) {
    global $serviceMap;

    $mappedName = $serviceMap[$serviceName] ?? $serviceName;

    $command = 'sudo systemctl stop ' . escapeshellarg($mappedName) . ' 2>&1';
    @exec($command);
    sleep(1);
    return checkServiceStatus($mappedName) === 'stopped';
}

// Reload Apache
function reloadApache() {
    $apacheService = 'apache2';
    $status = checkServiceStatus($apacheService);

    if ($status !== 'running') {
        return ['success' => false, 'error' => 'Apache is not running'];
    }

    // Try graceful reload via systemctl
    $command = 'sudo systemctl reload apache2 2>&1';
    $output = [];
    $returnCode = 0;
    @exec($command, $output, $returnCode);

    if ($returnCode === 0) {
        return ['success' => true, 'message' => 'Apache reloaded successfully'];
    }

    // Fallback: full restart
    $command = 'sudo systemctl restart apache2 2>&1';
    @exec($command, $output, $returnCode);

    if ($returnCode === 0) {
        return ['success' => true, 'message' => 'Apache restarted successfully'];
    }

    return ['success' => false, 'error' => 'Failed to reload or restart Apache'];
}

// Handle requests
try {
    switch ($action) {
        case 'status':
            $config = readLaragonIni();
            $services = [];
            
            $services = \LaragonDashboard\Core\Cache::get('service_status');
            if (!$services) {
                // ⚡ Bolt: Batch systemctl queries to avoid N+1 command execution
                $systemctlOutput = @shell_exec('systemctl is-active ' . implode(' ', array_map('escapeshellarg', array_values($serviceMap))) . ' 2>&1');
                $systemctlLines = array_filter(explode("\n", trim($systemctlOutput ?? '')));

                // Map systemctl output back to service names (output order matches input order)
                $serviceStatuses = [];
                $i = 0;
                foreach ($serviceMap as $key => $mappedName) {
                    $line = trim($systemctlLines[$i] ?? 'inactive');
                    $serviceStatuses[$key] = ($line === 'active') ? 'running' : 'stopped';
                    $i++;
                }

                // ⚡ Bolt: Single ss call for all port checks
                $ssOutput = @shell_exec('ss -tlnp 2>&1');

                foreach ($serviceMap as $key => $mappedName) {
                    $status = $serviceStatuses[$key] ?? 'stopped';
                    $usage = ($status === 'running') ? \LaragonDashboard\Core\Services::getResourceUsage($key) : ['cpu' => 0, 'ram' => 0, 'pid' => 0];

                    $port = $config[$key . 'Port'] ?? '';
                    if ($key === 'Mailpit') {
                        $sslPort = $config[$key . 'HTTPPort'] ?? null;
                    } else {
                        $sslPort = $config[$key . 'SSLPort'] ?? null;
                    }
                    $enabled = isset($config[$key . 'Enabled']) ? ($config[$key . 'Enabled'] == '1') : false;

                    $runningPorts = [];
                    if ($status === 'running') {
                        // ⚡ Bolt: Check ports against cached ss output
                        if (!empty($port) && $ssOutput && preg_match('/:' . preg_quote((string)$port, '/') . '\s/', $ssOutput)) {
                            $runningPorts[] = $port;
                        }
                        if (!empty($sslPort) && $ssOutput && preg_match('/:' . preg_quote((string)$sslPort, '/') . '\s/', $ssOutput)) {
                            $runningPorts[] = $sslPort;
                        }
                    }

                    $services[$key] = [
                        'status' => $status,
                        'port' => $port,
                        'ssl_port' => $sslPort,
                        'enabled' => $enabled,
                        'running_ports' => $runningPorts,
                        'usage' => $usage
                    ];
                }
                \LaragonDashboard\Core\Cache::set('service_status', $services, 30);
            }

            // Get disk usage for Laragon Root
            // ⚡ Bolt: Cache disk space calls to avoid redundant filesystem operations
            $totalSpace = disk_total_space(LARAGON_ROOT);
            $freeSpace = disk_free_space(LARAGON_ROOT);
            $usedSpace = $totalSpace - $freeSpace;

            $disk = [
                'total' => round($totalSpace / 1024 / 1024 / 1024, 2),
                'free' => round($freeSpace / 1024 / 1024 / 1024, 2),
                'used' => round($usedSpace / 1024 / 1024 / 1024, 2),
                'percent' => $totalSpace > 0 ? round(($usedSpace / $totalSpace) * 100, 1) : 0
            ];
            
            ob_clean();
            echo json_encode([
                'success' => true,
                'data' => [
                    'services' => $services,
                    'disk' => $disk
                ],
                'error' => null
            ]);
            ob_end_flush();
            break;
            
        case 'start':
            if (empty($serviceName)) {
                throw new Exception('Service name required');
            }
            
            $result = \LaragonDashboard\Core\Services::start($serviceName);
            if ($result) {
                \LaragonDashboard\Core\Cache::delete('service_status');
            }
            ob_clean();
            echo json_encode([
                'success' => $result,
                'data' => null,
                'error' => $result ? null : 'Failed to start service'
            ]);
            ob_end_flush();
            break;
            
        case 'stop':
            if (empty($serviceName)) {
                throw new Exception('Service name required');
            }
            
            $result = \LaragonDashboard\Core\Services::stop($serviceName);
            if ($result) {
                \LaragonDashboard\Core\Cache::delete('service_status');
            }
            ob_clean();
            echo json_encode([
                'success' => $result,
                'data' => null,
                'error' => $result ? null : 'Failed to stop service'
            ]);
            ob_end_flush();
            break;
            
        case 'reload':
            if ($serviceName !== 'Apache') {
                throw new Exception('Only Apache can be reloaded');
            }
            
            $result = reloadApache();
            ob_clean();
            echo json_encode($result);
            ob_end_flush();
            break;
            
        case 'save':
            // Save port configurations
            $services = $_POST['services'] ?? [];
            $config = readLaragonIni();
            
            foreach ($services as $key => $serviceData) {
                if (isset($serviceData['port'])) {
                    $config[$key . 'Port'] = $serviceData['port'];
                }
                // Mailpit uses HTTPPort, others use SSLPort
                if ($key === 'Mailpit') {
                    if (isset($serviceData['ssl_port']) && !empty($serviceData['ssl_port'])) {
                        $config[$key . 'HTTPPort'] = $serviceData['ssl_port'];
                    }
                } else {
                    if (isset($serviceData['ssl_port']) && !empty($serviceData['ssl_port'])) {
                        $config[$key . 'SSLPort'] = $serviceData['ssl_port'];
                    }
                }
                // Handle enabled checkbox
                if (isset($serviceData['enabled'])) {
                    $config[$key . 'Enabled'] = $serviceData['enabled'] == '1' ? '1' : '0';
                } elseif (isset($serviceData['enabled_check'])) {
                    // Fallback to enabled_check if enabled is not set
                    $config[$key . 'Enabled'] = $serviceData['enabled_check'] == 'on' ? '1' : '0';
                }
            }
            
            $result = writeLaragonIni($config);
            ob_clean();
            echo json_encode([
                'success' => $result,
                'message' => $result ? 'Configuration saved successfully' : 'Failed to save configuration'
            ]);
            ob_end_flush();
            break;
            
        case 'save_general':
            // Save general settings
            $config = readLaragonIni();
            
            // General settings fields
            $generalFields = [
                'DocumentRoot',
                'DataDirectory',
                'DomainSuffix',
                'HostnameFormat',
                'BackupInterval'
            ];
            
            foreach ($generalFields as $field) {
                if (isset($_POST[$field])) {
                    $config[$field] = trim($_POST[$field]);
                }
            }
            
            // Boolean fields (checkboxes)
            $booleanFields = [
                'StartAllAutomatically',
                'AutoCreateVirtualHosts',
                'RunOnWindowsStart',
                'RunMinimized',
                'AutoBackup',
                'AutoUpdate'
            ];
            
            foreach ($booleanFields as $field) {
                $value = isset($_POST[$field]) && $_POST[$field] == '1' ? '1' : '0';
                $config[$field] = $value;
                
                // Also set StartAll for backward compatibility
                if ($field === 'StartAllAutomatically') {
                    $config['StartAll'] = $value;
                }
            }
            
            $result = writeLaragonIni($config);
            ob_clean();
            echo json_encode([
                'success' => $result,
                'message' => $result ? 'General settings saved successfully' : 'Failed to save general settings'
            ]);
            ob_end_flush();
            break;
            
        default:
            throw new Exception('Invalid action');
    }
} catch (Exception $e) {
    \LaragonDashboard\Core\Logger::error("API services.php error: " . $e->getMessage());
    ob_clean();
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'data' => null,
        'error' => $e->getMessage()
    ]);
    ob_end_flush();
} catch (Error $e) {
    \LaragonDashboard\Core\Logger::error("API services.php fatal error: " . $e->getMessage());
    ob_clean();
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'data' => null,
        'error' => 'A fatal error occurred: ' . $e->getMessage()
    ]);
    ob_end_flush();
}

